model_name: "Monkey_GPT-1"
dataset_path: "~/datasets/wikipedia_Monkey.hdf5"
model_path: "~/model_weights/"
checkpoint_path: "~/model_weights/Monkey_GPT-1.pt"
chunk_size: 50
epochs: 2
num_layers: 1
num_heads: 1
d_model: 10
learning_rate: 2.5e-4
batch_size: 1000
warmup_epochs: 1
num_workers: 2
checkpoint_interval: 1
save_to_s3: True
s3_path: "s3://zima-data/model_weights/"
