model_name: "WALL-E_GPT-1"
dataset_path: "~/datasets/wikipedia_WALL-E_tokenized.hdf5"
model_path: "~/model_weights/"
checkpoint_path: "~/model_weights/WALL-E_GPT-1.pt"
chunk_size: 256
epochs: 20
num_layers: 5
num_heads: 5
d_model: 300
learning_rate: 2.5e-4
batch_size: 700
warmup_epochs: 2
num_workers: 2
checkpoint_interval: 1
save_to_s3: True
s3_path: "s3://zima-data/model_weights/"
